export interface Customer {
firstName: string,
lastName: string,
shopName: string,
degree: string,
ic: string,
dic: string,
phone: number,
email: string,
web: string,
country: string,
city: string,
zipCode: number,
street: string,
streetNumber: string,
id: string,
createdBy: string,
createdDate: string,
updatedBy: string,
updateDate: string,
deletedBy: string,
deletedDate: string
}